# Generated by Django 3.1.6 on 2021-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='Codes/'),
        ),
    ]
